### ISSUE TITLE
Add a `clear` method

### ISSUE THREAD

**Issue by davep** [davep/textual-canvas#2]
As per the subject, and asked for in #1 -- add a `clear` method for an existing canvas.

**Comment by davep** [comment]
Done. I'll probably push this out tomorrow some time. I was aiming to do it this evening but I got into a fight with Textual, Python 3.7 and (I think) markdown-it-py; and then with black, Python 3.8 and tomli.

I'm going back to Lisp I think, package management is *way* easier there...

(╯°□°）╯︵ ┻━┻

**Comment by TomJGooding** [comment]
Sorry my simple feature request seems to have opened a can of worms! Or should that be a package of pythons...

**Comment by davep** [comment]
Heh! I guess this is an issue that's going to "infect" all my toy projects now. Mainly the solution seems to be to give up on Python 3.7, which isn't a huge loss.
